"""period_prim_orani_eklendi

Revision ID: 10634e7c59ec
Revises: d68459728a41
Create Date: 2026-04-11 21:07:17.030748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10634e7c59ec'
down_revision = 'd68459728a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_rate', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period', schema=None) as batch_op:
        batch_op.drop_column('bonus_rate')

    # ### end Alembic commands ###
