"""category

Revision ID: 195c0c8981d7
Revises: 72c05089e706
Create Date: 2026-04-13 17:42:26.063871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195c0c8981d7'
down_revision = '72c05089e706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
