"""remove sale_price

Revision ID: 7f8354fd1760
Revises: 0183070183d1
Create Date: 2026-04-13 17:48:13.342665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8354fd1760'
down_revision = '0183070183d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.NUMERIC(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###
