"""ilk_kurulum

Revision ID: d68459728a41
Revises: 
Create Date: 2026-04-11 16:23:07.817465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68459728a41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_waste_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_type', sa.String(length=20), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_vat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('avg_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_sales_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('line_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste')
    op.drop_table('sale_item')
    op.drop_table('invoice_item')
    op.drop_table('sale')
    op.drop_table('product')
    op.drop_table('payment')
    op.drop_table('invoice')
    op.drop_table('expense')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('period')
    # ### end Alembic commands ###
