"""remove sale_price

Revision ID: f1f9aa9b496f
Revises: 7f8354fd1760
Create Date: 2026-04-14 16:46:45.469613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f9aa9b496f'
down_revision = '7f8354fd1760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###
